@startuml

class CategoriaCarros{
    - int : Id
    - String : Nombre
    - String : Descripcion
    - String : Caracteristica
    
}

class Autos{
    - int : Id
    - String : Marca
    - String : Modelo
    - String : Año
    - String : Precio
    - Categoria: Categoria_Id
}

class Personas{
    - int: Id
    - String: Nombre
    - String: Apellido
    - String: Edad 
    - String: Genero 
    - String: Direccion
}

class AutoPersonas{
    - int: Id 
    - String: Usuario
    - Autos: Autos_Id
    - Personas: Persona_Id
}

CategoriaCarros "1" -- "*" Autos : contiene
Personas "1" -- "*" AutoPersonas : contiene
Autos "1" -- "*" AutoPersonas : contiene 
@enduml